name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: testify876/fastapi:${{ github.sha }}

    # - name: Deploy to Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     script: |
    #       docker stop container_name || true
    #       docker rm container_name || true
    #       docker pull username/repo:${{ github.sha }}
    #       docker run -d -p 80:80 --name container_name username/repo:${{ github.sha }}
